apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: pg-data
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: postgres-disk
    namespace: default
  hostPath:
    path: /tmp
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
