apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-disk
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
